CREATE TABLE Users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE Roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE Users_Roles (
    user_id BIGINT REFERENCES Users(id),
    role_id INT REFERENCES Roles(id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE Requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    status VARCHAR(20) NOT NULL,
    text VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    user_id BIGINT REFERENCES Users(id)
);

INSERT INTO users (name) VALUES ('user1');
INSERT INTO users (name) VALUES ('user2');
INSERT INTO users (name) VALUES ('user3');
INSERT INTO users (name) VALUES ('operator1');
INSERT INTO users (name) VALUES ('operator2');
INSERT INTO users (name) VALUES ('admin1');

INSERT INTO roles (name) VALUES ('ROLE_USER');
INSERT INTO roles (name) VALUES ('ROLE_OPERATOR');
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');

INSERT INTO users_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (2, 3);
INSERT INTO users_roles (user_id, role_id) VALUES (3, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (4, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (4, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (5, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (5, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (6, 1);
INSERT INTO users_roles (user_id, role_id) VALUES (6, 2);
INSERT INTO users_roles (user_id, role_id) VALUES (6, 3);

/*INSERT INTO requests (status, text, created_at, user_id) VALUES ('DRAFT', 'text test req', '2016-06-22 19:10:25-07', 1);
INSERT INTO requests (status, text, created_at, user_id) VALUES ('DRAFT', 'text test req 2', '2017-06-22 20:10:25-07', 1);*/